### ISSUE TITLE
Crashes with -DWANT_DENSE on startup

### ISSUE THREAD

**Issue by danaki** [znort987/blockparser#22]
However it works without -DWANT_DENSE.

```
(gdb) where
#0  0x000000000042b105 in google::dense_hashtable<std::pair<unsigned char const* const, Chunk*>, unsigned char const*, Hash256Hasher, google::dense_hash_map<unsigned char const*, Chunk*, Hash256Hasher, Hash256Equal, google::libc_allocator_with_realloc<std::pair<unsigned char const* const, Chunk*> > >::SelectKey, google::dense_hash_map<unsigned char const*, Chunk*, Hash256Hasher, Hash256Equal, google::libc_allocator_with_realloc<std::pair<unsigned char const* const, Chunk*> > >::SetKey, Hash256Equal, google::libc_allocator_with_realloc<std::pair<unsigned char const* const, Chunk*> > >::copy_from(google::dense_hashtable<std::pair<unsigned char const* const, Chunk*>, unsigned char const*, Hash256Hasher, google::dense_hash_map<unsigned char const*, Chunk*, Hash256Hasher, Hash256Equal, google::libc_allocator_with_realloc<std::pair<unsigned char const* const, Chunk*> > >::SelectKey, google::dense_hash_map<unsigned char const*, Chunk*, Hash256Hasher, Hash256Equal, google::libc_allocator_with_realloc<std::pair<unsigned char const* const, Chunk*> > >::SetKey, Hash256Equal, google::libc_allocator_with_realloc<std::pair<unsigned char const* const, Chunk*> > > const&, unsigned long) [clone .local.85] (this=0x7fff5eb61810, ht=..., min_buckets_wanted=<optimized out>) at /usr/include/c++/4.6/bits/stl_construct.h:76
#1  0x000000000041d020 in __base_ctor (min_buckets_wanted=<optimized out>, ht=..., this=0x7fff5eb61810) at /usr/include/google/sparsehash/densehashtable.h:708
#2  google::dense_hashtable<std::pair<unsigned char const* const, Chunk*>, unsigned char const*, Hash256Hasher, google::dense_hash_map<unsigned char const*, Chunk*, Hash256Hasher, Hash256Equal, google::libc_allocator_with_realloc<std::pair<unsigned char const* const, Chunk*> > >::SelectKey, google::dense_hash_map<unsigned char const*, Chunk*, Hash256Hasher, Hash256Equal, google::libc_allocator_with_realloc<std::pair<unsigned char const* const, Chunk*> > >::SetKey, Hash256Equal, google::libc_allocator_with_realloc<std::pair<unsigned char const* const, Chunk*> > >::resize_delta(unsigned long) [clone .local.81] (this=0x645160, delta=<optimized out>) at /usr/include/google/sparsehash/densehashtable.h:599
#3  0x0000000000405cc2 in initHashtables () at /usr/include/google/sparsehash/densehashtable.h:649
#4  main (argc=<optimized out>, argv=<optimized out>) at parser.cpp:839
```

```
vagrant@precise64:~$ apt-show-versions libssl-dev build-essential g++-4.4 libboost-all-dev libsparsehash-dev git-core perl
build-essential/precise-updates uptodate 11.5ubuntu2.1
g++-4.4/precise uptodate 4.4.7-1ubuntu2
git-core/precise uptodate 1:1.7.9.5-1
libboost-all-dev/precise uptodate 1.48.0.2
libsparsehash-dev/precise uptodate 1.10-1build1
libssl-dev/precise-security uptodate 1.0.1-4ubuntu5.20
perl/precise-security uptodate 5.14.2-6ubuntu2.4
```

```
vagrant@precise64:~/blockparser$ git rev-parse HEAD
3294d0bf16a109382dbbf08d521e4a6e28bf8954
```

**Comment by znort987** [comment]
It looks like it runs out of memory in the hsah table allocation.
How much RAM do you have when you run this and how much swap space ?

**Comment by danaki** [comment]
Seems to work if I give more memory
